#!/usr/bin/env python
# -*- coding: utf-8 -*-

from vendor import requests
from vendor import parse

# The Source of Truth.
SOURCE_URI = 'http://jruby.org/files/downloads/index.html'

# The Parse template for finding the truth amongst the HTML.
PARSE_VERSION_TEMPLATE = '<a href=\'/files/downloads/{}/index.html\'>{}</a><br/>'


def yield_versions():
    """Discovers currently–released JRuby versions from jruby.org and
    Yields them as an iterator."""

    # Make the HTTP request.
    r = requests.get(SOURCE_URI)

    #
    for result in parse.findall(PARSE_VERSION_TEMPLATE, r.text):
        # Print each version release number.
        result = result[0]
        if 'rc' not in result.lower() and 'pre' not in result and 'community' not in result:
            yield result


def main():
    """Print each version number to stdout."""
    for version in yield_versions():
        print(version)


# If executed directly, run main automatically.
if __name__ == '__main__':
    main()
